### ISSUE TITLE
Wide character in print at /usr/bin/vendor_perl/msgconvert line 397, error with latest update (0.920)

### ISSUE THREAD

**Issue by poel22** [mvz/email-outlook-message-perl#34] opened 2021-05-03 08:52 UTC
Thank you for providing this software.

I have been unable to convert a specific email which I can provide if absolutely necessary (company email).

After trying around and recognizing it works in an ubuntu WSL (version 0.919), i tried to install the old version on manjaro (0.919) which successfully converts the mail. There the last output is "Wide character in print at /usr/bin/vendor_perl/msgconvert line 58.", but still the email is converted and on first sight includes everything important.

Environments where it doesn't work with 0.920:
Linux 5.9.16-1-MANJARO x86_64 GNU/Linux, AUR package "perl-email-outlook-message"
Alpine based image on same machine, with following packages installed:
```bash
apk add --no-cache --virtual .build-deps \
        perl-utils \
        perl-module-build \
        perl-app-cpanminus
    apk add perl-email-address-xs perl-doc perl-params-util
    cpanm Email::Outlook::Message
```
In the alpine container, the error message is exactly the same. After downgrading to version 0.919 it also works, but with slightly different "Wide character in print at /usr/bin/msgconvert line 62." as final output.

**Comment by mvz** [comment] 2021-05-03 09:00
This is possibly a duplicate of #30. A fix has been committed to master and will be part of the next release.

**Comment by poel22** [comment] 2021-05-03 09:00
Ok, thx for the quick response. Should I close this?

**Comment by mvz** [comment] 2021-05-03 09:03
> Should I close this?

Yes, please.

**Closed** 2021-05-03 09:18 UTC
